/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.pkgfinal;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import net.proteanit.sql.DbUtils;

/**
 *@version Oxygen.2 Release (4.7.2)
 *
 */
@SuppressWarnings("serial")
public class Idash extends JFrame {
   /**
   * Creates new form Idash
   */


  String email="";

  public Idash() {
    initComponents();
    getContentPane().setBackground(new Color(255,255,255));
    this.setTitle("Investor Dashboard");

  }


 public Idash(String email)
  {
    this.email=email;
    initComponents(); 
    getContentPane().setBackground(new Color(255,255,255));

  }

 public void fetch_Data()
  {
    try
    {
      Class.forName("com.mysql.jdbc.Driver");

     Connection conn = DriverManager.getConnection("jdbc:mysql://root@localhost:3306/project?autoReconnect=true&useSSL=false","arundhati","arundhati");


      Statement stmt=conn.createStatement();
      String sql="select iname,email,contact,location,market,capital from investor where email='"+this.email+"';";
      ResultSet rs=stmt.executeQuery(sql);
      jtable1.setModel(DbUtils.resultSetToTableModel(rs));

    }

    catch(ClassNotFoundException | SQLException e)
    {
      JOptionPane.showMessageDialog(null, e.getMessage() ,"Error", 1);
      System.out.println(e);


    }
  }
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */

  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jbutton1 = new javax.swing.JButton();
    jscrollpane1 = new javax.swing.JScrollPane();
    jtable1 = new javax.swing.JTable();
    jlabel1 = new javax.swing.JLabel();
  //  jbutton7 = new javax.swing.JButton(); //Search startup
    jbutton6 = new javax.swing.JButton(); //Invest
    jbutton8 = new javax.swing.JButton();   //refresh and view
    jbutton9 = new javax.swing.JButton();   //view investment status

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowOpened(java.awt.event.WindowEvent evt) {
        formWindowOpened(evt);
      }
    });

    jbutton1.setText("Logout");
    jbutton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jbutton1ActionPerformed(evt);
      }
    });

    jtable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
          {null, null, null},
          {null, null, null},
          {null, null, null},
          {null, null, null}
        },
        new String [] {
            "Title 1", "title 2", "title 3"
        }
        ));
    jtable1.setRowHeight(70);
    jscrollpane1.setViewportView(jtable1);

    jlabel1.setIcon(new javax.swing.ImageIcon("investors.jpg","image"));
    try {
      Image img = ImageIO.read(getClass().getResource("investors.jpg"));
      jlabel1.setIcon(new ImageIcon(img));
    } catch (Exception e1) {
      System.out.println(e1);
    }

  //  jbutton7.setText("Search Startups");

    jbutton6.setText("Invest");
    jbutton6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jbutton6ActionPerformed(evt);
      }
    });

    jbutton8.setText("Refresh and View");
    jbutton8.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jbutton8ActionPerformed(evt);
      }
    });

    jbutton9.setText("View Investment status");
    jbutton9.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jbutton9ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(38, 38, 38)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jscrollpane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(190, 190, 190)
                            .addComponent(jbutton8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(24, 192, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                      //      .addComponent(jbutton7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)
                            .addComponent(jbutton6, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(55, 55, 55)
                            .addComponent(jbutton9, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jlabel1)
                            .addGap(175, 175, 175)
                            .addComponent(jbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(44, Short.MAX_VALUE))))
        );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jlabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbutton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
            .addComponent(jscrollpane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jbutton8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(34, 34, 34)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
           //     .addComponent(jbutton7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jbutton6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jbutton9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(39, 39, 39))
        );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    First f=new First();
    f.setVisible(true);
    this.setVisible(false);
  }//GEN-LAST:event_jButton1ActionPerformed

  private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    // TODO add your handling code here:
    fetch_Data();
  }//GEN-LAST:event_formWindowOpened

  private void jbutton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    // TODO add your handling code here:
    Investpage i=new Investpage(email);
    i.setVisible(true);

  }//GEN-LAST:event_jButton6ActionPerformed

  private void jbutton9ActionPerformed(java.awt.event.ActionEvent evt) 
  { //GEN-FIRST:event_jButton9ActionPerformed
    // TODO add your handling code here:
    Invest i=new Invest(email);
    i.setVisible(true);

  }//GEN-LAST:event_jButton9ActionPerformed





  private void jbutton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    // TODO add your handling code here:
    fetch_Data();
  }//GEN-LAST:event_jButton8ActionPerformed


  public static void main(String[] args) throws ClassNotFoundException, InstantiationException, IllegalAccessException, javax.swing.UnsupportedLookAndFeelException {
    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
      if ("Nimbus".equals(info.getName())) {
        javax.swing.UIManager.setLookAndFeel(info.getClassName());
        break;
      }
    }

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Idash().setVisible(true);
      }
    });
  }

  private static void extracted(Exception ex) {
    java.util.logging.Logger.getLogger(Idash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jbutton1;
  private javax.swing.JButton jbutton6;
 // private javax.swing.JButton jbutton7;
  private javax.swing.JButton jbutton8;
  private javax.swing.JButton jbutton9;
  private javax.swing.JLabel jlabel1;
  private javax.swing.JScrollPane jscrollpane1;
  private javax.swing.JTable jtable1;
  // End of variables declaration//GEN-END:variables
}
