/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.pkgfinal;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**@  Oxygen.2 Release (4.7.2)
 *
 *
 */

public class Invest extends javax.swing.JFrame {

  private static final long serialVersionUID = 1L;
  /**
   * Creates new form Invest
   */

  String email = " ";

  public Invest() {
    initComponents();
    this.setTitle("Investment status");
  }

  public Invest(String email) {
    this.email = email;
    initComponents();
    getContentPane().setBackground(new Color(255, 255, 255));

  }

  public void fetch_Data() {
    try {
      Class.forName("com.mysql.jdbc.Driver");

      Connection conn = DriverManager.getConnection(
          "jdbc:mysql://root@localhost:3306/project?autoReconnect=true&useSSL=false", "arundhati",
          "arundhati");

      Statement stmt = conn.createStatement();
      String sql = "select sname,amount from invest where iemail='" + email + "';";
      ResultSet rs = stmt.executeQuery(sql);
      jtable1.setModel(DbUtils.resultSetToTableModel(rs));

         }

    catch (ClassNotFoundException | SQLException e) {
      JOptionPane.showMessageDialog(null, e.getMessage(), "Error", 1);
      System.out.println(e);

    }
  }

  public void getValue() {
    Float xamt = null;
    Float xcapital = null;

    try {

      Class.forName("com.mysql.jdbc.Driver");

      Connection conn = DriverManager.getConnection(
          "jdbc:mysql://root@localhost:3306/project?autoReconnect=true&useSSL=false", "arundhati",
          "arundhati");

      String sql1 = "select sum(amount) as amt from invest  where iemail='" + email + "';";
      String sql2 = "select capital as cap from investor  where email='" + email + "';";
      PreparedStatement pst1 = conn.prepareStatement(sql1);
      PreparedStatement pst2 = conn.prepareStatement(sql2);

      ResultSet rs1 = pst1.executeQuery();
      if (rs1.next()) {
        xamt = rs1.getFloat("amt");
      }

      ResultSet rs2 = pst2.executeQuery();
      if (rs2.next()) {
        xcapital = rs2.getFloat("cap");
      }

      captf.setText(String.valueOf(xcapital));
      titf.setText(String.valueOf(xamt));

      pst1.close();
      pst2.close();
      conn.close();

    }

    catch (ClassNotFoundException | SQLException e) {
      JOptionPane.showMessageDialog(null, e.getMessage(), "Error", 1);
      System.out.println(e);

    }

  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */

  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jscrollpane1 = new javax.swing.JScrollPane();
    jtable1 = new javax.swing.JTable();
    captf = new javax.swing.JTextField();
    titf = new javax.swing.JTextField();
    jlabel1 = new javax.swing.JLabel();
    jlabel2 = new javax.swing.JLabel();
    jbutton1 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowOpened(java.awt.event.WindowEvent evt) {
        formWindowOpened(evt);
      }
    });

    jtable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][] { { null, null }, { null, null }, { null, null }, { null, null } },
        new String[] { "Startup", "Amount Invested" }));
    jscrollpane1.setViewportView(jtable1);

    jlabel1.setText("Capital");

    jlabel2.setText("Total Invested");

    jbutton1.setText("Back");
    jbutton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
            layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabel1).addGap(84, 84, 84)
                .addComponent(captf, javax.swing.GroupLayout.PREFERRED_SIZE, 145,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        .addGroup(layout.createSequentialGroup()
            .addGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup().addGap(69, 69, 69).addComponent(
                        jscrollpane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup().addGap(95, 95, 95)
                        .addComponent(jlabel2).addGap(55, 55, 55)
                        .addComponent(titf, javax.swing.GroupLayout.PREFERRED_SIZE, 137,
                            javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup().addGap(189, 189, 189).addComponent(
                        jbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94,
                        javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(78, Short.MAX_VALUE)));
    layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup().addGap(23, 23, 23)
            .addComponent(jscrollpane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98,
                javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(37, 37, 37)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(captf, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jlabel1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29,
                Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jlabel2).addComponent(titf, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(28, 28, 28).addComponent(jbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
                javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap()));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void formWindowOpened(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowOpened
    // TODO add your handling code here:
    fetch_Data();

    getValue();
  }// GEN-LAST:event_formWindowOpened

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    this.setVisible(false);
  }// GEN-LAST:event_jButton1ActionPerformed

  /**
   * @param args
   *          the command line arguments
   */
  public static void main(String[] args) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
          .getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Invest.class.getName()).log(java.util.logging.Level.SEVERE,
          null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Invest.class.getName()).log(java.util.logging.Level.SEVERE,
          null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Invest.class.getName()).log(java.util.logging.Level.SEVERE,
          null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Invest.class.getName()).log(java.util.logging.Level.SEVERE,
          null, ex);
    }
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Invest().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField captf;
  private javax.swing.JButton jbutton1;
  private javax.swing.JLabel jlabel1;
  private javax.swing.JLabel jlabel2;
  private javax.swing.JScrollPane jscrollpane1;
  private javax.swing.JTable jtable1;
  private javax.swing.JTextField titf;
  // End of variables declaration//GEN-END:variables
}
