/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author arundhati
 */
public class investpage extends javax.swing.JFrame {

    /**
     * Creates new form investpage
     */
    
    String email="";
    
    public investpage() {
        initComponents();
    }
    
    public investpage(String email)
    {
        this.email=email;
        initComponents();
        getContentPane().setBackground(new Color(255,255,255));
        this.setTitle("Invest Now");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        snametf = new javax.swing.JTextField();
        amttf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Startup Name");

        jLabel2.setText("Amount to Invest");

        jButton1.setText("Confirm Investment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(snametf)
                            .addComponent(amttf, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButton1)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(snametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(amttf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String xsname=snametf.getText();
        Float xamt=Float.parseFloat(amttf.getText());
        Float xcapital = null;
        Float xfund = null;
        
        try
        
           
        {
            String xemail="";
            Class.forName("com.mysql.jdbc.Driver");
         
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","arundhati","arundhati");
            
            String sql5="select email as email from investor where email='"+this.email+"';";
            PreparedStatement pst5=conn.prepareStatement(sql5);
            ResultSet rs5=pst5.executeQuery();
            if(rs5.next())
                xemail=rs5.getString("email");
            
            
            
            
            String insert="insert into invest values(?,?,?);";
            PreparedStatement stmt=conn.prepareStatement(insert);
        
        
            stmt.setString(1, xemail);
            stmt.setString(2, xsname);
            stmt.setFloat(3, xamt);
            
            int i =stmt.executeUpdate();
            
            String sql="Select capital from investor where email='"+email+"';";
            
            PreparedStatement pst=conn.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            if(rs.next())
                xcapital=rs.getFloat("capital");
            
        }
        
            catch(ClassNotFoundException | SQLException e)
     {
         JOptionPane.showMessageDialog(null, e.getMessage() ,"Error", 1);
          System.out.println(e);
        
     }
       if(xcapital< xamt)
           javax.swing.JOptionPane.showMessageDialog(this, "No sufficient amount !");
       
       else{
           xcapital=xcapital-xamt;
           try{
               
            Class.forName("com.mysql.jdbc.Driver");
         
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","arundhati","arundhati");
            
            Statement stmt1=conn.createStatement();
            String insert1="update investor set capital='"+xcapital+"' where email='"+email+"';";
            stmt1.executeUpdate(insert1);
            stmt1.close();
            
            String sql2="Select fund from startup where name='"+xsname+"';";
            PreparedStatement pst1=conn.prepareStatement(sql2);
            ResultSet rs=pst1.executeQuery();
            
            if(rs.next())
            {xfund=rs.getFloat("fund");
            pst1.close();}
            
            xfund=xfund+xamt;
            
            Statement stmt2=conn.createStatement();
            String insert2="Update startup set fund='"+xfund+"' where email='"+email+"';";
            
           stmt2.executeUpdate(insert2);
           stmt2.close();
           conn.close();
           
           javax.swing.JOptionPane.showMessageDialog(this, "Connected to Mentor !");    
           this.setVisible(false);
           
           } 
           catch (SQLException ex) {
                Logger.getLogger(investpage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(investpage.class.getName()).log(Level.SEVERE, null, ex);
            }
           
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(investpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(investpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(investpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(investpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new investpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amttf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField snametf;
    // End of variables declaration//GEN-END:variables
}
